/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReferenceRouteImport } from './routes/api-reference'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiPublicDailyReportRouteImport } from './routes/api/public/daily-report'
import { Route as ApiPublicPublishMetersRouteImport } from './routes/api/public/publish-meters'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDailyReportRoute = ApiPublicDailyReportRouteImport.update({
  id: '/api/public/daily-report',
  path: '/api/public/daily-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPublishMetersRoute = ApiPublicPublishMetersRouteImport.update({
  id: '/api/public/publish-meters',
  path: '/api/public/publish-meters',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRoute
  '/settings': typeof SettingsRoute
  '/api/public/daily-report': typeof ApiPublicDailyReportRoute
  '/api/public/publish-meters': typeof ApiPublicPublishMetersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRoute
  '/settings': typeof SettingsRoute
  '/api/public/daily-report': typeof ApiPublicDailyReportRoute
  '/api/public/publish-meters': typeof ApiPublicPublishMetersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRoute
  '/settings': typeof SettingsRoute
  '/api/public/daily-report': typeof ApiPublicDailyReportRoute
  '/api/public/publish-meters': typeof ApiPublicPublishMetersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-reference'
    | '/settings'
    | '/api/public/daily-report'
    | '/api/public/publish-meters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-reference'
    | '/settings'
    | '/api/public/daily-report'
    | '/api/public/publish-meters'
  id:
    | '__root__'
    | '/'
    | '/api-reference'
    | '/settings'
    | '/api/public/daily-report'
    | '/api/public/publish-meters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiReferenceRoute: typeof ApiReferenceRoute
  SettingsRoute: typeof SettingsRoute
  ApiPublicDailyReportRoute: typeof ApiPublicDailyReportRoute
  ApiPublicPublishMetersRoute: typeof ApiPublicPublishMetersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference': {
      id: '/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daily-report': {
      id: '/api/public/daily-report'
      path: '/api/public/daily-report'
      fullPath: '/api/public/daily-report'
      preLoaderRoute: typeof ApiPublicDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/publish-meters': {
      id: '/api/public/publish-meters'
      path: '/api/public/publish-meters'
      fullPath: '/api/public/publish-meters'
      preLoaderRoute: typeof ApiPublicPublishMetersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiReferenceRoute: ApiReferenceRoute,
  SettingsRoute: SettingsRoute,
  ApiPublicDailyReportRoute: ApiPublicDailyReportRoute,
  ApiPublicPublishMetersRoute: ApiPublicPublishMetersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
